### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by pointout** [iMi-digital/imi_mm_changelanguage#2]
ich habe das modul per Composer installiert und bekomme folgende Fehlermeldung:

``` php
Warning: Missing argument 4 for iMi\MMChangeLanguage\ImiMMChangeLanguageObserver::translateMMUrls(), called in /var/www/contao.web.local/public_html/system/modules/changelanguage/ModuleChangeLanguage.php on line 204 and defined in system/modules/imi_mm_changelanguage/classes/ImiMMChangeLanguageObserver.php on line 87

#0 system/modules/imi_mm_changelanguage/classes/ImiMMChangeLanguageObserver.php(87): __error(2, 'Missing argumen...', '/var/www/contao...', 87, Array)
#1 system/modules/changelanguage/ModuleChangeLanguage.php(204): iMi\MMChangeLanguage\ImiMMChangeLanguageObserver->translateMMUrls(Array, 'de', Array)
#2 system/modules/core/modules/Module.php(282): ModuleChangelanguage->compile()
#3 system/modules/changelanguage/ModuleChangeLanguage.php(72): Contao\Module->generate()
#4 system/modules/core/library/Contao/Controller.php(313): ModuleChangelanguage->generate()
#5 composer/vendor/contao/core/system/modules/core/library/Contao/InsertTags.php(465): Contao\Controller::getFrontendModule('92')
#6 system/modules/core/library/Contao/Controller.php(686): Contao\InsertTags->replace('...', false)
#7 system/modules/core/classes/FrontendTemplate.php(100): Contao\Controller::replaceInsertTags('...', false)
#8 system/modules/core/pages/PageRegular.php(190): Contao\FrontendTemplate->output(true)
#9 system/modules/core/controllers/FrontendIndex.php(267): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#10 index.php(20): Contao\FrontendIndex->run()
#11 {main}
```

Der alias ist ein normaler (nicht übersetzter) Alias. Parameter auto_item.
(metamodels/core    dev-master (31d9da66))

**Comment by amenk** [comment]
Das Modul benötigt eine Änderung an ChangeLanguage welche noch nicht released ist,

Wenn du diesen Branch nimmst:

https://github.com/terminal42/contao-changelanguage/tree/hotfix/2.2.10

Sollte es funktionieren.

**Comment by pointout** [comment]
perfekt. Danke!
